/opt/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:4737: UserWarning: Byte tensor for key_padding_mask in nn.MultiheadAttention is deprecated. Use bool tensor instead.
  "Byte tensor for key_padding_mask in nn.MultiheadAttention is deprecated. Use bool tensor instead."
mode : sgdet
save_path : data/
model_path : pretrained_models/sgdet.tar
data_path : ../ActionGenome/dataset/ag/
datasize : large
ckpt : None
optimizer : adamw
lr : 1e-05
nepoch : 10
enc_layer : 1
dec_layer : 3
bce_loss : False
-------loading annotations---------slowly-----------
--------------------finish!-------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
There are 1737 videos and 54429 valid frames
48 videos are invalid (no person), remove them
20 videos are invalid (only one frame), remove them
8472 frames have no human bbox in GT, remove them!
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
word vector location: data data
loading word vectors from data/data/glove.6B.200d.pt
word vector location: /home/cong/Dokumente/neural-motifs-master/data /hom
loading word vectors from data//home/cong/Dokumente/neural-motifs-master/data/glove.6B.200d.pt
__background__ -> __background__ 
fail on __background__
**************************************************
CKPT pretrained_models/sgdet.tar is loaded
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    for b, data in enumerate(dataloader):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfshome/students/aa211327/STTran/dataloader/action_genome.py", line 169, in __getitem__
    im = imread(os.path.join(self.frames_path, name)) # channel h,w,3
  File "/opt/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename
ValueError: Could not find a format to read the specified file in single-image mode
